/*
 * Look4Sat. Amateur radio satellite tracker and pass predictor.
 * Ported to HarmonyOS ArkTS from the Android Kotlin original (GPL-3.0).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

export const ASTRONOMICAL_UNIT: number = 1.49597870691E8;
export const DEG2RAD: number = 0.017453292519943295;
export const RAD2DEG: number = 57.29577951308232;
export const EARTH_RADIUS: number = 6378.137;
export const EARTH_ROT_PER_SID_DAY: number = 1.00273790934;
export const EPSILON: number = 1.0E-12;
export const FLAT_FACT: number = 3.35281066474748E-3;
export const J3_HARMONIC: number = -2.53881E-6;
export const MIN_PER_DAY: number = 1.44E3;
export const SEC_PER_DAY: number = 8.6400E4;
export const SOLAR_RADIUS: number = 6.96000E5;
export const SPEED_OF_LIGHT: number = 2.99792458E8;
export const PI: number = 3.141592653589793;
export const PI_2: number = PI / 2.0;
export const TWO_PI: number = PI * 2.0;
export const TWO_THIRDS: number = 2.0 / 3.0;
export const CK2: number = 5.413079E-4;
export const CK4: number = 6.209887E-7;
export const XKE: number = 7.43669161E-2;